//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_checklist_medidas_N01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Check_checklist_medidas_N01()
        {
            this.Check_checklist_medidas_acciones_N01 = new HashSet<Check_checklist_medidas_acciones_N01>();
        }
    
        public int id { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public Nullable<int> Q11 { get; set; }
        public Nullable<int> Q12 { get; set; }
        public Nullable<int> Q13 { get; set; }
        public Nullable<int> Q14 { get; set; }
        public Nullable<int> Q15 { get; set; }
        public Nullable<int> Q16 { get; set; }
        public Nullable<int> Q17 { get; set; }
        public Nullable<int> Q18 { get; set; }
        public Nullable<int> Q19 { get; set; }
        public Nullable<int> Q20 { get; set; }
        public Nullable<int> Q21 { get; set; }
        public Nullable<int> Q22 { get; set; }
        public Nullable<int> Q23 { get; set; }
        public Nullable<int> Q24 { get; set; }
        public Nullable<int> Q25 { get; set; }
        public Nullable<int> Q26 { get; set; }
        public Nullable<int> Q27 { get; set; }
        public Nullable<int> Q28 { get; set; }
        public Nullable<int> Q29 { get; set; }
        public Nullable<int> Q30 { get; set; }
        public Nullable<int> Q31 { get; set; }
        public Nullable<int> Q32 { get; set; }
        public Nullable<int> Q33 { get; set; }
        public Nullable<int> Q34 { get; set; }
        public Nullable<int> Q35 { get; set; }
        public Nullable<int> Q36 { get; set; }
        public Nullable<int> Q37 { get; set; }
        public string QR1 { get; set; }
        public string QR2 { get; set; }
        public string QR3 { get; set; }
        public string QR4 { get; set; }
        public string QR5 { get; set; }
        public string QR6 { get; set; }
        public string QR7 { get; set; }
        public string QR8 { get; set; }
        public string QR9 { get; set; }
        public string QR10 { get; set; }
        public string QR11 { get; set; }
        public string QR12 { get; set; }
        public string QR13 { get; set; }
        public string QR14 { get; set; }
        public string QR15 { get; set; }
        public string QR16 { get; set; }
        public string QR17 { get; set; }
        public string QR18 { get; set; }
        public string QR19 { get; set; }
        public string QR20 { get; set; }
        public string QR21 { get; set; }
        public string QR22 { get; set; }
        public string QR23 { get; set; }
        public string QR24 { get; set; }
        public string QR25 { get; set; }
        public string QR26 { get; set; }
        public string QR27 { get; set; }
        public string QR28 { get; set; }
        public string QR29 { get; set; }
        public string QR30 { get; set; }
        public string QR31 { get; set; }
        public string QR32 { get; set; }
        public string QR33 { get; set; }
        public string QR34 { get; set; }
        public string QR35 { get; set; }
        public string QR36 { get; set; }
        public string QR37 { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string Razon_social { get; set; }
        public string telefono { get; set; }
        public string No_empleados { get; set; }
        public string Nombre_Contacto { get; set; }
        public Nullable<int> Cat_I { get; set; }
        public Nullable<int> Cat_II { get; set; }
        public Nullable<int> Cat_III { get; set; }
        public Nullable<int> Cat_V { get; set; }
        public Nullable<int> Cat_IV { get; set; }
        public Nullable<int> id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_checklist_medidas_acciones_N01> Check_checklist_medidas_acciones_N01 { get; set; }
    }
}
