//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_checklist_N01
    {
        public int id { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string Razon_social { get; set; }
        public string telefono { get; set; }
        public string No_empleados { get; set; }
        public string Nombre_Contacto { get; set; }
    }
}
