//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_checklist_medidas_acciones_N01
    {
        public int id { get; set; }
        public int id_checklist_37 { get; set; }
        public int id_medida { get; set; }
        public string accion { get; set; }
        public int id_empresa { get; set; }
        public Nullable<int> id_centro_trabajo { get; set; }
        public string departamento { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string file_evidencia { get; set; }
        public string estatus { get; set; }
        public Nullable<int> nivel { get; set; }
    
        public virtual Check_checklist_medidas_N01 Check_checklist_medidas_N01 { get; set; }
    }
}
