//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E360_Cuestionario_Resultado_N01
    {
        public int id_cuestionario_resultado { get; set; }
        public Nullable<int> id_cuestionario_trabajador { get; set; }
        public string Evaluado { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public Nullable<int> Q11 { get; set; }
        public Nullable<int> Q12 { get; set; }
        public Nullable<int> Q13 { get; set; }
        public Nullable<int> Q14 { get; set; }
        public Nullable<int> Q15 { get; set; }
        public Nullable<int> Q16 { get; set; }
        public Nullable<int> Q17 { get; set; }
        public Nullable<int> Q18 { get; set; }
        public Nullable<int> Q19 { get; set; }
        public Nullable<int> Q20 { get; set; }
        public Nullable<int> Q21 { get; set; }
        public Nullable<int> Q22 { get; set; }
        public Nullable<int> Q23 { get; set; }
        public Nullable<int> Q24 { get; set; }
        public Nullable<int> Q25 { get; set; }
        public Nullable<int> Q26 { get; set; }
        public Nullable<int> Q27 { get; set; }
        public Nullable<int> Q28 { get; set; }
        public Nullable<int> Q29 { get; set; }
        public Nullable<int> Q30 { get; set; }
        public Nullable<int> Q31 { get; set; }
        public Nullable<int> Q32 { get; set; }
        public Nullable<int> Q33 { get; set; }
        public Nullable<int> Q34 { get; set; }
        public Nullable<int> Q35 { get; set; }
        public Nullable<int> Q36 { get; set; }
        public Nullable<int> Q37 { get; set; }
        public Nullable<int> Q38 { get; set; }
        public Nullable<int> Q39 { get; set; }
        public Nullable<int> Q40 { get; set; }
        public Nullable<int> Q41 { get; set; }
        public Nullable<int> Q42 { get; set; }
        public Nullable<int> Q43 { get; set; }
        public Nullable<int> Q44 { get; set; }
        public Nullable<int> Q45 { get; set; }
        public Nullable<int> Q46 { get; set; }
        public Nullable<int> Q47 { get; set; }
        public Nullable<int> Q48 { get; set; }
        public Nullable<int> Q49 { get; set; }
        public Nullable<int> Q50 { get; set; }
        public Nullable<int> C_I { get; set; }
        public Nullable<int> C_II { get; set; }
        public Nullable<int> C_III { get; set; }
        public Nullable<int> C_IV { get; set; }
        public Nullable<int> C_V { get; set; }
        public Nullable<int> C_VI { get; set; }
        public Nullable<int> C_VII { get; set; }
        public Nullable<int> C_VIII { get; set; }
        public Nullable<int> C_IX { get; set; }
        public Nullable<int> C_X { get; set; }
        public Nullable<int> C_XI { get; set; }
        public Nullable<int> C_XII { get; set; }
        public Nullable<int> C_XIII { get; set; }
        public Nullable<int> C_XIV { get; set; }
        public Nullable<int> C_XV { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<int> id_CT_Evaluado { get; set; }
    
        public virtual ERGOS_Cuestionarios_Trabajador_N01 ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
    }
}
