//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Usuarios_N01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERGOS_Usuarios_N01()
        {
            this.ERGOS_Buzon_N01 = new HashSet<ERGOS_Buzon_N01>();
        }
    
        public int id_user { get; set; }
        public string User_Nombre { get; set; }
        public string User_Password { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> downAccess_at { get; set; }
        public Nullable<int> id_centro_trabajo { get; set; }
        public Nullable<int> id_cuestionario_trabajador { get; set; }
    
        public virtual ERGOS_Centros_Trabajo_N01 ERGOS_Centros_Trabajo_N01 { get; set; }
        public virtual ERGOS_Cuestionarios_Trabajador_N01 ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        public virtual ERGOS_Empresas_N01 ERGOS_Empresas_N01 { get; set; }
        public virtual ERGOS_Roles_N01 ERGOS_Roles_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Buzon_N01> ERGOS_Buzon_N01 { get; set; }
    }
}
