//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Cuestionarios_Resultados_N01
    {
        public int id_Cuestionario_Resultado { get; set; }
        public Nullable<int> id_cuestionario_trabajador { get; set; }
        public Nullable<int> id_respuesta { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public Nullable<int> id_encuesta { get; set; }
        public Nullable<int> Calificacion { get; set; }
    
        public virtual ERGOS_Cuestionarios_Trabajador_N01 ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        public virtual ERGOS_Preguntas_N01 ERGOS_Preguntas_N01 { get; set; }
        public virtual ERGOS_Respuestas_N01 ERGOS_Respuestas_N01 { get; set; }
    }
}
