//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Empresas_N01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERGOS_Empresas_N01()
        {
            this.ERGOS_Centros_Trabajo_N01 = new HashSet<ERGOS_Centros_Trabajo_N01>();
            this.ERGOS_Cuestionarios_Trabajador_N01 = new HashSet<ERGOS_Cuestionarios_Trabajador_N01>();
            this.ERGOS_Usuarios_N01 = new HashSet<ERGOS_Usuarios_N01>();
        }
    
        public int id_empresa { get; set; }
        public string Razon_Social { get; set; }
        public string Telefono { get; set; }
        public string Contacto_Nombre { get; set; }
        public string Email { get; set; }
        public int id_encuesta { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string RFC { get; set; }
        public string Domicilio { get; set; }
        public string Actividad_Principal { get; set; }
        public Nullable<System.DateTime> Fecha_Aplicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Centros_Trabajo_N01> ERGOS_Centros_Trabajo_N01 { get; set; }
        public virtual ERGOS_Cuestionarios_N01 ERGOS_Cuestionarios_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Cuestionarios_Trabajador_N01> ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Usuarios_N01> ERGOS_Usuarios_N01 { get; set; }
    }
}
