//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Centros_Trabajo_N01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERGOS_Centros_Trabajo_N01()
        {
            this.ERGOS_Cuestionarios_Trabajador_N01 = new HashSet<ERGOS_Cuestionarios_Trabajador_N01>();
            this.ERGOS_Usuarios_N01 = new HashSet<ERGOS_Usuarios_N01>();
        }
    
        public int id_centro_trabajo { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string Nombre_centro_trabajo { get; set; }
        public Nullable<int> No_emplados { get; set; }
        public Nullable<System.DateTime> Fecha_Auditoria { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string Comentarios { get; set; }
        public string direccion { get; set; }
        public string Actividad_principal { get; set; }
        public string Razon_Social { get; set; }
    
        public virtual ERGOS_Empresas_N01 ERGOS_Empresas_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Cuestionarios_Trabajador_N01> ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Usuarios_N01> ERGOS_Usuarios_N01 { get; set; }
    }
}
