//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Buzon_N01
    {
        public int id { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string tipo { get; set; }
        public string cat_sugerencia { get; set; }
        public string cat_sugerencia_desc { get; set; }
        public string denuncia_relacionada { get; set; }
        public string denuncia_involucrados { get; set; }
        public string denuncia_hechos_desc { get; set; }
        public string denuncia_frecuencia { get; set; }
        public string denuncia_soy { get; set; }
        public string denuncia_mas_involucrados { get; set; }
        public Nullable<int> alta_admin { get; set; }
        public string notas { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ERGOS_Usuarios_N01 ERGOS_Usuarios_N01 { get; set; }
    }
}
