//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_login_N01
    {
        public int id_log { get; set; }
        public string Name_user { get; set; }
        public string Pass_user { get; set; }
        public Nullable<System.DateTime> Event_datetime { get; set; }
        public Nullable<int> Login_status { get; set; }
        public string Comment { get; set; }
    }
}
