//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_Cuestionarios_Trabajador_N01
    {
        public int id_log { get; set; }
        public int id_cuestionario_trabajador { get; set; }
        public string id_trabajador { get; set; }
        public Nullable<int> id_encuesta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Estado_Civil { get; set; }
        public string Nivel_Esudios { get; set; }
        public string Ocupacion { get; set; }
        public string Departamento { get; set; }
        public string Tipo_puesto { get; set; }
        public string Tipo_Contratacion { get; set; }
        public string Tipo_Jornada { get; set; }
        public string Rotacion_Turno { get; set; }
        public Nullable<int> Experiencia_puesto_actual { get; set; }
        public Nullable<int> Experiencia_puesto_laboral { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> Tipo_Personal { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> No_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Email { get; set; }
        public Nullable<int> Mail_Status { get; set; }
        public Nullable<int> Survey_Status { get; set; }
        public Nullable<int> Canalizacion { get; set; }
        public string deleted_by { get; set; }
        public Nullable<int> id_centro_trabajo { get; set; }
    }
}
